### ISSUE TITLE
How about the Result on Pascal VOC?

### ISSUE THREAD

**Issue by BestSongEver** [chriszhenghaochen/CCnet_Tensorflow#1]
I wonder the results of your code.
About your Old Version, you said: Enhance baseline from 68.1% to 71.1% (In paper is 81.9%)
How about this version?
Thanks a lot.

**Comment by chriszhenghaochen** [comment]
The different between mine and paper:
paper: 81% the paper using inception as basenet and use VOC07+12 training dataset, and use cascade in fast rcnn.
Mine: 71.1% (average), using vgg16 as basebnet, use VOC07 as training dataset, put cascade in rpn in my old version. I also try to implement the cascade in fast-rcnn in new version, but I don't see much enhancement only do in fast-rcnn

**Comment by BestSongEver** [comment]
@chriszhenghaochen Thanks for your quick reply. You are so kind.
So, about your new version, you also put cascade in rpn, not fast-rcnn?
By the way, how about using resnet as basebnet ?  I noticed the CCnet_Tensorflow/lib/nets/resnet_v1.py in your code, so maybe you tried to use resnet as basebnet.

**Comment by chriszhenghaochen** [comment]
I attempt couple experments, trying both fast-rcnn, rpn cascade and both in VGG16 cascade, but I didn't see that fast-rcnn has much improvement in VOC0712, maybe my implementation isn't so right they are here
https://github.com/chriszhenghaochen/CCnet_Tensorflow/tree/master/other_setting

I, then, headed forward to resnet using Mxnet and do cascade in frcn res101, because this original repo can't really support parallel well. 
https://github.com/chriszhenghaochen/CCnet_mxnet
It has a very limited improvement
